### ISSUE TITLE
Reminder Configuation

### ISSUE THREAD

**Issue by carlygreenehill** [bcgov/EPIC-FLOW#261]
**As a** Super User/Creator

**I want** to update the Reminder  Configuration

**so that** I can change the configuration whenever it is required

## **Acceptance Criteria**
The Super User/Should be able to go and update the Reminder Configuration as and when required
### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

# Tasks
- [ ] #262
- [ ] #263
- [x] #264
- [ ] #278
- [x] #279

**Comment by dinesh-aot** [comment]
# Tasks
- [ ] Create Draft Report Configuration form
- [ ] Create BPM Model for the form
- [ ] Create report-api endpoints for Draft Report Configuration
